<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6karFuK\srcApp_KernelProdDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6karFuK/srcApp_KernelProdDebugContainer.php') {
    touch(__DIR__.'/Container6karFuK.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdDebugContainer::class, false)) {
    \class_alias(\Container6karFuK\srcApp_KernelProdDebugContainer::class, srcApp_KernelProdDebugContainer::class, false);
}

return new \Container6karFuK\srcApp_KernelProdDebugContainer([
    'container.build_hash' => '6karFuK',
    'container.build_id' => '47a247ae',
    'container.build_time' => 1615820854,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6karFuK');
