<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'liste' => [[], ['_controller' => 'App\\Controller\\ListeController::liste'], [], [['text', '/liste']], [], []],
    'search' => [[], ['_controller' => 'App\\Controller\\SearchController::index'], [], [['text', '/search']], [], []],
    'history' => [[], ['_controller' => 'App\\Controller\\SearchController::history'], [], [['text', '/history']], [], []],
];
