<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerASnPHQB\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerASnPHQB/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerASnPHQB.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerASnPHQB\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerASnPHQB\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ASnPHQB',
    'container.build_id' => '4eed3b9f',
    'container.build_time' => 1615831706,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerASnPHQB');
