<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJc8Xjxe\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJc8Xjxe/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJc8Xjxe.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJc8Xjxe\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerJc8Xjxe\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Jc8Xjxe',
    'container.build_id' => '9dff0c53',
    'container.build_time' => 1615811650,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJc8Xjxe');
